#Prometheus + Alertmanager config

alertmanager:
  enabled: true

  config:
    route:
      receiver: "slack"
    receivers:
      - name: "slack"
        slack_configs:
          - api_url: "https://hooks.slack.com/services/XXXXX"
            channel: "#alerts"

grafana:
  enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
